### ISSUE TITLE
ftr bag-special

### ISSUE THREAD

**Issue by VB2webD** [VB2webD/capstone#11]
## Value statement - a requirement, not a solution

As a **busy customer**
I need **check out the premixed bags**
so that **i can quickly purchase what i want**

## Acceptance criteria

- [ ] create bag details page

## Tasks

- [ ] add onclick to bags that links to details page
- [ ] create dynamic route to details page
- [ ] implement static routes / getstaticpros
- [ ] display image
- [ ] display bag details and variants on detail page
- [ ] implement counter on details page
- [ ] style page

## Size

small
