### ISSUE TITLE
Checkout page & confirm Order

### ISSUE THREAD

**Issue by VB2webD** [VB2webD/capstone#13]
## Value statement - a requirement, not a solution

As a **customer**
I need **to check my order and click purchase to finalise my choices**
so that **can actually get the items i selected**

## Description
Create a checkout page that displays the items, prices and a buy bottuon.
the buy button will send the user to to billing page allowing to select the shipping and payment information.

## Acceptance criteria

- [ ] create a checkout page
- [ ] create the billing page

## Tasks

- [ ] create a checkout page
- [ ] create a billing page
- [ ] list purchases including prices to give the user an overview
- [ ] bonus add variants displayed under the main item displaying their amount and pricing
- [ ] create purchase button to link to billing page
- [ ] billing page : create an option for shipping adress and a layout to add new adresses
- [ ] create a payment option with a layout to add new options
- [ ] create a buy button to finalise the purchase
- [ ] clear shopping cart on purchase
- [ ] create alert with animation on clicking buy
- [ ] style the pages

## Size

 large
