### ISSUE TITLE
Backend implementation -bags

### ISSUE THREAD

**Issue by VB2webD** [VB2webD/capstone#4]
## Value statement - a requirement, not a solution

As a **Shopowner**
I need **to provide my shop inventory for my customers**
so that **they can browse my wares**

## Description
I want to provide my inventory through a backend to ensure that the user can see but not alter the information of the items in stock

## Acceptance criteria

- [x] bags are displayed on the special page

## Tasks

- [x] create db for the inventory on mongo db
- [x] create collection for the Bags on mongo db
- [x] create visual dummy page to test the fetches
- [x] create getBags helper funktion
- [x] implement helper Funktion in pages via GetStaticProps (bags)

## Size

(large)
