### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by VB2webD** [VB2webD/capstone#7]
## Value statement - a requirement, not a solution

As a **(customer)**
I need **(to click the shopping Cart)**
so that **(which items i currently aim to purchase)**

## Acceptance criteria

- [ ] create a shopping Cart
- [ ] see bought items in Cart
- [ ] delete items from cart

## Tasks

- [ ] create shopping Cart Component
- [ ] create Image for shopping Cart
- [ ] create Item Counter to see how many items are in Cart
- [ ] styled shopping Cart in Header
- [ ] on Click, see List of items in Card
- [ ] create Buy botton to link to checkout page
- [ ] create Provider for shopping Cart
- [ ] create local Storage hook to save selected items locally
- [ ] create delete funktion on listed items
- [ ] style buy link

## Size

(large)
