### ISSUE TITLE
Item display with onClick details in dynamic pages

### ISSUE THREAD

**Issue by VB2webD** [VB2webD/capstone#9]
## Value statement - a requirement, not a solution

As a **Customer**
I need **to select an Item**
so that **i can see details and add the item to my card**

## Description (Text, Scribble, Wireframe, Design)
Create an Item Component
## Acceptance criteria

- [x]  fetch items and display them on the shop page
- [x] Create a details page for each item that displays the counter component, a picture and details

## Tasks

- [x] add a helper function in utils/data to fetch items from mongo
- [x] fetch items on Shop Page
- [x] display items 
- [x] create dynamic itemdetail page
- [x] display dynamic route onClick to see details of selected item
- [x] add counter component to details page
- [x] embed information on details page
- [x] add isTiny to counter
- [x] style item details

## Size

large
